-- WolnyTermin — schemat poczatkowy (MVP)
-- Konwencje:
--   * wszystkie znaczniki czasu absolutnego: timestamptz
--   * godziny pracy (powtarzalne, "kazdy poniedzialek 9-17"): time + day_of_week
--   * day_of_week: 1 = poniedzialek ... 7 = niedziela (zgodnie z ISO-8601 i java.time.DayOfWeek)

-- Potrzebne do constraintu EXCLUDE na rezerwacjach (porownanie '=' po bigint w indeksie GiST).
CREATE EXTENSION IF NOT EXISTS btree_gist;


-- ---------------------------------------------------------------- firma

CREATE TABLE company (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT        NOT NULL,
    slug         TEXT        NOT NULL,
    category     TEXT        NOT NULL,
    description  TEXT,
    street       TEXT,
    postal_code  TEXT,
    city         TEXT,
    phone        TEXT,
    email        TEXT,
    active       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT company_slug_uq UNIQUE (slug)
);

CREATE INDEX company_city_idx ON company (city);
CREATE INDEX company_category_idx ON company (category);


-- Godziny otwarcia firmy. Przerwa w srodku dnia = dwa wiersze na ten sam dzien.
CREATE TABLE company_opening_hours (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT   NOT NULL REFERENCES company (id) ON DELETE CASCADE,
    day_of_week SMALLINT NOT NULL,
    opens_at   TIME     NOT NULL,
    closes_at  TIME     NOT NULL,
    CONSTRAINT company_opening_hours_dow_ck   CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT company_opening_hours_range_ck CHECK (closes_at > opens_at),
    CONSTRAINT company_opening_hours_uq       UNIQUE (company_id, day_of_week, opens_at)
);


-- ---------------------------------------------------------------- pracownik

CREATE TABLE employee (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT      NOT NULL REFERENCES company (id) ON DELETE CASCADE,
    first_name TEXT        NOT NULL,
    last_name  TEXT        NOT NULL,
    email      TEXT,
    phone      TEXT,
    active     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX employee_company_idx ON employee (company_id);


-- ---------------------------------------------------------------- usluga

CREATE TABLE service (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           BIGINT        NOT NULL REFERENCES company (id) ON DELETE CASCADE,
    name                 TEXT          NOT NULL,
    description          TEXT,
    price_amount         NUMERIC(10,2) NOT NULL,
    price_currency       CHAR(3)       NOT NULL DEFAULT 'PLN',
    duration_minutes     INTEGER       NOT NULL,
    -- bufor na sprzatanie/przygotowanie po wizycie; wchodzi do liczenia slotow,
    -- ale nie jest czescia czasu widocznego dla klienta
    buffer_after_minutes INTEGER       NOT NULL DEFAULT 0,
    active               BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT service_duration_ck CHECK (duration_minutes > 0),
    CONSTRAINT service_buffer_ck   CHECK (buffer_after_minutes >= 0),
    CONSTRAINT service_price_ck    CHECK (price_amount >= 0),
    CONSTRAINT service_name_uq     UNIQUE (company_id, name)
);

CREATE INDEX service_company_idx ON service (company_id);


-- Ktory pracownik wykonuje ktora usluge (N:N — jedna usluga moze byc robiona przez kilku).
CREATE TABLE employee_service (
    employee_id BIGINT NOT NULL REFERENCES employee (id) ON DELETE CASCADE,
    service_id  BIGINT NOT NULL REFERENCES service (id)  ON DELETE CASCADE,
    PRIMARY KEY (employee_id, service_id)
);

CREATE INDEX employee_service_service_idx ON employee_service (service_id);


-- ---------------------------------------------------------------- dostepnosc pracownika

-- Stale godziny pracy. Przerwa (np. lunch) = dwa wiersze na ten sam dzien.
CREATE TABLE working_hours (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT   NOT NULL REFERENCES employee (id) ON DELETE CASCADE,
    day_of_week SMALLINT NOT NULL,
    starts_at   TIME     NOT NULL,
    ends_at     TIME     NOT NULL,
    CONSTRAINT working_hours_dow_ck   CHECK (day_of_week BETWEEN 1 AND 7),
    CONSTRAINT working_hours_range_ck CHECK (ends_at > starts_at),
    CONSTRAINT working_hours_uq       UNIQUE (employee_id, day_of_week, starts_at)
);

CREATE INDEX working_hours_employee_idx ON working_hours (employee_id);


-- Jednorazowe nieobecnosci: urlop, zwolnienie, recznie zablokowany termin.
CREATE TABLE time_off (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT      NOT NULL REFERENCES employee (id) ON DELETE CASCADE,
    starts_at   TIMESTAMPTZ NOT NULL,
    ends_at     TIMESTAMPTZ NOT NULL,
    reason      TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT time_off_range_ck CHECK (ends_at > starts_at)
);

CREATE INDEX time_off_employee_range_idx ON time_off (employee_id, starts_at, ends_at);


-- ---------------------------------------------------------------- klient

-- Rezerwacja "jako gosc" jest dozwolona — brak hasla w MVP.
-- Konto z logowaniem dolozymy osobna migracja przy JWT.
CREATE TABLE customer (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT        NOT NULL,
    last_name  TEXT,
    email      TEXT        NOT NULL,
    phone      TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX customer_email_uq ON customer (lower(email));


-- ---------------------------------------------------------------- rezerwacja

CREATE TABLE booking (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          BIGINT        NOT NULL REFERENCES company (id),
    employee_id         BIGINT        NOT NULL REFERENCES employee (id),
    service_id          BIGINT        NOT NULL REFERENCES service (id),
    customer_id         BIGINT        NOT NULL REFERENCES customer (id),
    starts_at           TIMESTAMPTZ   NOT NULL,
    -- koniec wizyty wraz z buforem — to jest zakres, ktory blokuje kalendarz
    ends_at             TIMESTAMPTZ   NOT NULL,
    status              TEXT          NOT NULL,
    -- cena z momentu rezerwacji; cennik moze sie pozniej zmienic
    price_amount        NUMERIC(10,2) NOT NULL,
    price_currency      CHAR(3)       NOT NULL DEFAULT 'PLN',
    notes               TEXT,
    cancellation_reason TEXT,
    cancelled_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    -- pole dla @Version w JPA (optimistic locking)
    version             BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT booking_range_ck  CHECK (ends_at > starts_at),
    CONSTRAINT booking_status_ck CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW'))
);

-- Ochrona przed double-bookingiem na poziomie bazy.
-- Dwie aktywne rezerwacje tego samego pracownika nie moga miec nakladajacych sie zakresow.
-- Baza odrzuci druga rownolegla transakcje niezaleznie od tego, co zrobi kod aplikacji.
ALTER TABLE booking
    ADD CONSTRAINT booking_no_overlap
    EXCLUDE USING gist (
        employee_id WITH =,
        tstzrange(starts_at, ends_at, '[)') WITH &&
    )
    WHERE (status <> 'CANCELLED');

CREATE INDEX booking_company_starts_idx  ON booking (company_id, starts_at);
CREATE INDEX booking_employee_starts_idx ON booking (employee_id, starts_at);
CREATE INDEX booking_customer_idx        ON booking (customer_id);
